const express = require('express');
const app = express();
const axios = require('axios');

const PORT = process.env.FEC_PROXY_PORT || 8080
const BOOKING_PORT = process.env.BOOKING_PORT || 50003
const BOOKING_HOSTNAME = process.env.BOOKING_HOSTNAME || 'localhost';
const CAROUSEL_PORT = process.env.CAROUSEL_PORT || 50002
const CAROUSEL_HOSTNAME = process.env.CAROUSEL_HOSTNAME || 'localhost';
const ABOUT_PORT = process.env.ABOUT_PORT || 50001
const ABOUT_HOSTNAME = process.env.ABOUT_HOSTNAME || 'localhost';
const REVIEWS_PORT = process.env.REVIEWS_PORT || 50000
const REVIEWS_HOSTNAME = process.env.REVIEWS_HOSTNAME || 'localhost';

app.use(express.json());

// app.use('/:id', express.static(__dirname + '/public'));

const static = `
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://kit.fontawesome.com/4723f324c2.js" crossorigin="anonymous"></script>
    <script src="https://hrr43fecheskett.s3.us-east-2.amazonaws.com/styles/installCSS.js" crossorigin="anonymous"></script>
    <title>HRR43 FEC TeamHan!</title>
    </head>
    <body>
    <div style="margin: 0 6% 0 6%;">
    <div style="display: flex">
    <div id="booking" ></div>
    <div id="carousel" ></div>
    </div>
    <div id="about"></div>
    <div id="reviews" style="margin-top: 12px"></div>
    </div>
    <script src="http://${BOOKING_HOSTNAME}:${BOOKING_PORT}/bundle.js" ></script>
    <script src="http://${CAROUSEL_HOSTNAME}:${CAROUSEL_PORT}/bundle.js" ></script>
    <script src="http://${ABOUT_HOSTNAME}:${ABOUT_PORT}/bundle.js" ></script>
    <script src="http://${REVIEWS_HOSTNAME}:${REVIEWS_PORT}/bundle.js" ></script>
  </body>
</html>`


const favicon = new Buffer.from('AAABAAEAKCgAAAEAIABoGgAAFgAAACgAAAAoAAAAUAAAAAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAa4+ZF197hCk+VW4pJjJUKR8vUw4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUHGHPkVe\nc/wpPl3/FytS/xUiQP8UGizVCwsPfgwJC0wjMTguAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsszLAFN2nNxLb6D/QGqd/zphmf8r\nToP/J0Ju/xooSv8TGCv/DA8c/xYfM6MMFCAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG6LoT1bf6j/WIGy/0Rtpv8zXZf/L1mR/ypRhv8mR3v/\nIThj/x8yV/8hL0//Hi9T4CM4XTMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAABgg5xpR26e/zZXi/8gO3H/GThw/ydQjP8kTor/JkyH/ydLfv8qT3v/MlWA\n/yNAaP8uTXzxSHCeJwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAWn+gl1Fwpf9DY6T/OFKX/ytHiv8oRoP/J0yG/y9ak/8oUYX/MVmK/z9nk/84YYv/MFWB/1iD\nq8iUuNcRAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE1vlsk0T4L/\nECNV/xowXv8lQ3H/IUFx/zJelP82ZZ7/M2CT/zlklP9FcKD/Qm6b/0Vxnf9kjbL/nbzawAAAAAAA\nAAAAAAAAAHKGliBZb355uMzXxtLg5FkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEZYvqRWaa/0RvpP9Jc6X/Tnep\n/0l1qf9AcKf/OWql/zlrn/86aJv/RHGg/0p3o/9Vg6v/Z5S3/56+1/1LZ5E2AAAAAA8RHCtVYm+r\nrb/K/67E0P/d6vE9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABZgZ0wWH2j/0dplP9GbJ3/R2+h/1R9s/9VhLr/PW2q/0l6\ns/8+caj/PW6k/0d3p/9Ofqn/Xoqz/32kxf+hv9n/MkBX4QkKDyktNT1manqG/520wf+/09//8Pr6\nVQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAY4anej1kmP8iPG3/JUF3/ytOjv8nS4z/S3mz/05/uv9VhLv/SXmx/zpupv86\nbaP/UoSy/16Mt/+Eq8r/pcLa/1ltgP8ZMmbuJT5s4iIpNv9dcoH/wtLa//P9+2UAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAF2Hq5hXgbb/TXiy/zNdoP85Zaj/MFyf/0Z3sv9ol8n/ZJLD/05/t/8/cq3/O2+o/2KPvf9kkbr/\nf6PC/5u2yv95lK3/HkF9/1uDuP+Pp8L/MTtD/2uDk/+twspgAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABhia2aY428/2CN\nwv82Zqn/L1yg/0p6tf9tmMn/c5vL/2eTwv9ah7v/Tny0/1CCtf9olcD/cZzB/093nf8fLUv/OE1q\n/yU5Yf9ke5r/VHuz/1Fqiv8lLDj/hZei9LjKxzkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYYqummiSvv9JfrX/UIG1/zdmqP9p\nk8T/g6nO/3Gdxv9rlcX/XYu9/1uKvP9Xhrb/ZZTA/3ukxv9VfKH/KzdS/yoxQv8oOE7/CgoR/yc+\nbf9kfqL/HB8l/1Jlb//L3uKHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG6Uulp1ncP/VISz/06CuP84aaj/XY28/1ODsv9eiLX/\naI+2/1SCr/9RhbX/VIa3/02Csv9ii7P/OlV7/xcZJv8NDBH/DAcK/wsLD/8nNUj/XXSF/09cZP9d\ndIH/1+jt6tDc2AgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAABVfpk+bpS3/0hsmP9Ee7H/RHav/1qFsf9VgK7/Wn2q/5Gcnv8xQVf/J0p7\n/zlsof8zZZ3/J0x//w0YK/8JCAn/CQcJ/wsIC/8nMD//QlBh/2Fzfv93jJf/j6Wy/+Py9v/U4uAz\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAQGB1PniRqP9ucnb/THOW/0t7rf8rUYn/GTRo/0RXc/94fX7/JT5h/yZOhf8gRn//HER+/xQq\nVf8ODhT/FhYb/xUUGv8qLTf/MzpI/yAmL/9nfor/nLG7/7fN1//l8vb/3+jmZAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADZIWXlRXGr/\nTlhr/0Z6rf84aaT/IEN6/xwuVf8eLlH/JT9m/ytOev8kTID/HUB4/yFGfv8SIEL/ExIa/xkeK/9O\nYG3/Ki40/wwMD/8QFR//bYma/7TK1f/Q4ej/9/39/9rk32oAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhKTjdNU5r/0pxnP9woMv/YpHA\n/1aBsf9firj/W4e0/1B3pP9NeKj/QXCm/ylYkv8bOGn/EhYl/yMoN/9CVWf/RlZj/x4iKv8SEBb/\nO1Rk/6K/z/+sws7/6PT3//X7+v/N19BQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALD1P6V2IsP9ql8X/b53J/2eYyf9dkMX/X5DE/1aI\nvP9ajL7/VYi5/1CFt/81Z57/ECVL/z5TZ/8fLED/eZGf/yUvN/9YbHn/HyQw/1x9kf9ylKn/0OTr\n/8vg6P/x9/X1xtHIDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAKCkqEhojL/9Wf6v/YI6+/1yOv/9cjMD/WovC/16Oxf9bi8H/VIm8/1eNvv9O\ngrX/KV6X/xo1Xv9pip7/WnKI/3qPmf9kfIr/S2Bz/zVHWf9CWGf/gZuu/83k7P/V6vH/4+zqxgAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nACkyOFMPEhv/RGuU/2GMu/9tlsT/Y5TF/2WUxP9rmMb/bZvK/1yQwf9Uh7n/MWWe/x5Jg/8pSnH/\nZYie/3uYqv9sgo7/RVVj/2B4iP8+Tlr/L0RT/5Kxw/+11OD/6vf7/9fj35gAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqNUBnGB0n/yk/\nWf9Hc6L/SnWk/1qKuf9kl8T/ZpnF/22axf9WiLr/MWWh/yVOhf8YKVH/HS5N/yc6Tf9NaHv/hZyn\n/3GMnP9ccH3/ZHaB/2SFl/9Ubn3/vtjk//P8/P/U4Nw2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFxwiZhETGP8REh7/FR40/xAYMP8V\nKEj/M1R7/zlbhv89YIz/M1mI/y9Tgf8gNVL/FiA3/xcfMP8UGCD/TGJx/3qUov+Qqrn/N0hU/4mj\nsP9CVmb/VXGE/9Hl7P/v9/f5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4LDlsQDRH/DwsQ/w8MEP8OCQz/CwkN/wwNGP8PDxz/\nExUl/xEVJv8tOUv/Dw8X/w4ME/8NCQv/DAgL/zZGU/+Jqbn/dYyX/3uVov9WZXD/IzE9/4WouP/a\n7vP/8fn44AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAARDRIIDw8T0A8KDP8RDA//EQ8T/w4LDf8LCAn/CwgJ/w4JC/8NCQr/DgwP\n/wwIC/8RDA7/DAkK/wsJCf8fLDn/m7jF/0haZP+gv8z/JjI6/1Rlcf+cusn/3O/1//L39sMAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAABkdIlcPDhD/DgsN/w8MD/8PCgz/CwkJ/woICP8MCAj/CwgI/woICP8MCQr/DwoM/w0K\nCv8PDQ3/OktW/3qZp/9QZXH/krC+/x8rM/+Cnan/XH+R/+Du8//v9fNaAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nEhIVmhAOD/8SDhH/EAsN/wwKCv8KCAj/CwcI/woICP8MCgn/DAkK/w0ICf8QCwz/Eg8Q/zJBTf9i\neoj/RVxq/2WAjP9idYD/MUBL/2yKnf/m8vTV8fz6AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABoYGxESDQ7YEAsM\n/xINDv8NCwv/DgoL/w4JCv8MCAj/CwkJ/woJCf8NCQr/DwoK/w4MDP8cIir/MzxE/3qRnf81QEj/\nPElW/z5Waf/M3ePr5vDrKgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAsLFBEOENkUDxD/GBUW/xEM\nDf8OCQr/DgkK/xgYG/8MCgr/DgkK/xAOEP8bHyj/MDpG/z1PXf9qgY7/JDRD/0Zgcf+pv8X02ebo\nOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXFxkZExESshEODv8SDw//Eg8Q/xIQEP8g\nIiX/HR8j/yQrMv9hdHv/X3V+/1hsdf9he4n/dJCg/3+apf7H2N+V1N7aLQAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkcGgsWGxpwKzEv/BsaG/8TExT/FhcZ/xUZG8tGU1qz\nl6yxbay/wlGSq7KjlrC2zJSus8WsxMdGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHyMhiA/TUxFUmNlfFNlYk8AAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////8AAAD//////wAAAP//////AAAA//////8AAAD/8H//\n/wAAAP/gD///AAAA/+AD//8AAAD/wAH//wAAAP/AAP//AAAA/8AAf/8AAAD/wABw/wAAAP/AACD/\nAAAA/4AAAP8AAAD/gAAA/wAAAP+AAAD/AAAA/4AAAH8AAAD/gAAAfwAAAP+AAAA/AAAA/4AAAD8A\nAAD/gAAAPwAAAP+AAAA/AAAA/4AAAD8AAAD/gAAAPwAAAP8AAAB/AAAA/wAAAH8AAAD/AAAAfwAA\nAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+AAAD/AAAA/8AAAP8AAAD/wAAB/wAAAP/gAAP/AAAA\n//AAB/8AAAD/+AAf/wAAAP/+H///AAAA//////8AAAD//////wAAAP//////AAAA//////8AAAA=\n', 'base64');
app.get("/favicon.ico", function(req, res) {
 res.statusCode = 200;
 res.setHeader('Content-Length', favicon.length);
 res.setHeader('Content-Type', 'image/x-icon');
 res.setHeader("Cache-Control", "public, max-age=2592000");                // expires after a month
 res.setHeader("Expires", new Date(Date.now() + 2592000000).toUTCString());
 res.end(favicon);
});

app.post('/api/booking/:id', (req, res) => {
  axios.post(`http://${BOOKING_HOSTNAME}:${BOOKING_PORT}${req.url}`, {...req.body})
  .then(response => response.data)
  .then(data => res.send(data))
  .catch(err => console.log('error at proxy serving about',err));
});


app.get('/api/carousel/:id', (req, res) => {
  axios.get(`http://${CAROUSEL_HOSTNAME}:${CAROUSEL_PORT}${req.url}`)
  .then(response => response.data)
  .then(data => res.send(data))
  .catch(err => console.log('error at proxy serving about',err));
});

app.get('/api/about/:id', (req, res) => {
  axios.get(`http://${ABOUT_HOSTNAME}:${ABOUT_PORT}${req.url}`)
  .then(response => response.data)
  .then(data => res.send({data}))
  .catch(err => console.log('error at proxy serving about',err));
});

app.get('/api/reviews/:id', (req, res) => {
  axios.get(`http://${REVIEWS_HOSTNAME}:${REVIEWS_PORT}${req.url}`)
  .then(response => response.data)
  .then(data => res.send(data))
  .catch(err => console.log('error at proxy serving about',err));
});

app.get('/:id', function(req, res) {
  res.send(static);
})

let portReport = (!process.env.BOOKING_PORT) ? "undefined" : BOOKING_PORT;
console.log(`Booking proxy module accessing port:${BOOKING_PORT}`);
console.log('BOOKING_PORT Environnment Variable is', portReport,"\n");

portReport = (!process.env.CAROUSEL_PORT) ? "undefined" : CAROUSEL_PORT;
console.log(`Carousel proxy module accessing port:${CAROUSEL_PORT}`);
console.log('CAROUSEL_PORT Environnment Variable is', portReport,"\n");

portReport = (!process.env.ABOUT_PORT) ? "undefined" : ABOUT_PORT;
console.log(`About proxy module accessing port:${ABOUT_PORT}`);
console.log('ABOUT_PORT Environnment Variable is', portReport,"\n");

portReport = (!process.env.REVIEWS_PORT) ? "undefined" : REVIEWS_PORT;
console.log(`Reviews proxy module accessing port:${REVIEWS_PORT}`);
console.log('REVIEWS_PORT Environnment Variable is', portReport,"\n");

app.listen(PORT, console.log(`Listening on port ${PORT}`));